### ISSUE TITLE
Node.js 16 deprecated

### ISSUE THREAD

**Issue by echokos** [TryGhost/action-deploy-theme#101]
I was receiving 2 errors about Node.js 16 deprecation. I changed actions/checkout@v3 to v4 and that eliminated one of them.  Unsure of how to fix the last one as it looks like the script here still explicitly uses Node 16 in action.yaml

Error: _Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: TryGhost/action-deploy-theme@v1._

After fixing this, the example script in the description should be updated as well.

**Comment by daniellockyer** [comment]
@echokos Thanks for the report! We've fixed this so if you're using the `v1` tag, it should not be an issue any longer 🙂
