### ISSUE TITLE
action.yml missing `theme-name` config var

### ISSUE THREAD

**Issue by mrkwse** [TryGhost/action-deploy-theme#22]
`theme-name`  does not appear in action.yml and so causes a warning when run as follows: 

```Unexpected input 'theme-name', valid inputs are ['api-url', 'api-key', 'exclude', 'file']```

**Comment by mrkwse** [comment]
As per #23, the key is used by the action, but missing from actions.yml

**Comment by daniellockyer** [comment]
Fixed by #24
