### ISSUE TITLE
Getting Error: connect ECONNREFUSED 127.0.0.1:2368

### ISSUE THREAD

**Issue by Shubhamai** [TryGhost/action-deploy-theme#27]
Hey, I am getting the error `Error: connect ECONNREFUSED 127.0.0.1:2368` while using the actions

![Annotation 2020-06-22 122638](https://user-images.githubusercontent.com/51819922/85258152-96fbf980-b484-11ea-9d93-06d998e33031.png)

I have tried many things but nothing is working out. My Repository is [here](https://github.com/Shubhamai/website)

Thanks in Advance for helping me out. 🙂

**Comment by ErisDS** [comment]
GitHub actions can't work with a local site - it needs to be available over the internet. If you're developing locally then you should be able to see changes without needing the action.

If you need more help please visit https://forum.ghost.org
