### ISSUE TITLE
Error deploying to Ghost blog

### ISSUE THREAD

**Issue by sovereignhodler** [TryGhost/action-deploy-theme#67]
I've used action-deploy-theme for multiple blogs but with my most recent one it's failing. I tried pretty much everything but can't figure it out.

Running Ghost 4.40.0 on Yunohost.

Tried both with a Casper theme and Edition theme.

Error: Resource not found
    at /home/runner/work/_actions/TryGhost/action-deploy-theme/v1.5.0/dist/index.js:8160:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.5.0/dist/index.js:2009:9) {
  name: undefined,
  errorType: 'NotFoundError'
}

Any ideas?

**Comment by russkiimike** [comment]
Adding onto the issue with the same exact error; I am on a digital ocean droplet

Older versions don't work either :(

**Comment by daniellockyer** [comment]
Hey @russkiimike and @sovereignhodler!

This was actually due to a bug in v4.40.0. Please update to v4.41.0 using Ghost-CLI to resolve this 🙂
